version: "3.1"
services:
  mysql:
    image: mysql:latest
    networks:
      - backend
    restart: always
    container_name: mysql-app
    command: --init-file /tmp/data/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/tmp/data/init.sql
  app:
    build:
      ./app
    depends_on:
      - mysql
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=mysql-app
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=DEV
    networks:
      - backend
      - frontend
  httpd:
    image: httpd:latest
    ports:
      - "80:80"
    networks:
      - frontend
    volumes:
      - ./index.html/:/usr/local/apache2/htdocs/index.html
    container_name: 'httpd'
    environment:
      - APP_HOST=app
networks:
  backend:
  frontend:

